<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $popup = $block->getPath(); ?>
<?php $_product = $block->getProduct(); ?>
<?php if ($popup !== false) : ?>
    <style>
        #two {
            position: relative;
            float: right;
        }
    </style>
<?php endif; ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />

        <?php if ($popup !== false) : ?>
            <div id="popup-modal" style="display:none;">
                <?php echo($block->getFront()) ?>
            </div>
        <?php endif; ?>

        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()):?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($popup !== false) : ?>
            <div id="two" style="padding-top: 46px;
                             width: 59px;
                             height: 30px;">
                <a href="#" id="click-me">Click Me <img src='<?php echo $block->getPath(); ?>'
                                                        style="position: absolute;  width: 18px;margin-left: 4px;"
                                                        alt="icon">
                </a>
            </div>
        <?php endif; ?>
        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>
<?php if ($popup !== false) : ?>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function ($, modal) {
                var options = {
                    clickableOverlay: false,
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Size Chart',
                    buttons: [],
                };
                var popup = modal(options, $('#popup-modal'));
                $("#click-me").on('click', function () {
                    $("#popup-modal").modal("openModal");
                });
            }
        );

    </script>
    <style type="text/css">
        .modal-popup .modal-inner-wrap {
            width: 50%;
        }
    </style>
<?php endif; ?>
